[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sharp = "6NLhWY23DxVyReB9m5uPakQbN13yJj7mveZNXsvxtfKy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --inline-diffs tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

# clone all invoked programs

[[test.genesis]]
address = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
program = "programs/pump.so"

[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "programs/raydium.so"

[[test.genesis]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
program = "programs/openbook.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://mainnet.helius-rpc.com/?api-key=4d612394-b5d0-46a2-b702-700ca9e1b0d5"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# clone all necessary accounts to test raydium swaps

# amm
[[test.validator.clone]]
address = "GCCNLvpp6wVPWUaXRguXPCv84g2utWYXXfiqcy6y5zg4"

# amm open orders
[[test.validator.clone]]
address = "EsXYKKYuBMxSRgV6d6ExRZeJB9iZiPs4JGamPdsSRMZn"

# amm target orders
[[test.validator.clone]]
address = "FFms2iYnwKfXAuTqmP12z7uqD4fRHr4E9bxUtt5hY7yo"

# amm coin vault
[[test.validator.clone]]
address = "5UrrK6d4TxnMj5ejTxAcabJfSyn58de4eaYuTnibPgV3"

# amm pc vault
[[test.validator.clone]]
address = "4YHFVkhULspUPGc8MBsvfaBhXLEzfnoBU6rVyhT2qmSk"

# market
[[test.validator.clone]]
address = "65VnQdkc78GctbqYpXaMPmaTMfUUedp6jp43z5ZLftmC"

# market bids
[[test.validator.clone]]
address = "6ksp1MZFoUUAzBJMbW1VcSiLG3iXdxzUXHrB9ZYjetYp"

# market asks
[[test.validator.clone]]
address = "2y3fT7VkhhwC5FD4qpP3RbEbCYRC7wv4mwupDf4FsKKk"

# market event queue
[[test.validator.clone]]
address = "BDNPVv8bM5ew7aXWGXNJ4C9HmENJfbA5ZAnbHi7Htssj"

# market coin vault
[[test.validator.clone]]
address = "67wM6L6KHn4Nu72AKQNjWV854sGmgPVvJV3VN8vTHvxx"

# market pc vault
[[test.validator.clone]]
address = "4CknBkuczy4tUss7aEoCqV27Bt7oGMem8RtR1dvjkfpz"

# out mint
[[test.validator.clone]]
address = "nLKhEUbWB3xx3Rr9DJDWGBEUraJY3mUyhgy3axYDqF3"

# clone all necessary accounts to test pump swaps

# global
[[test.validator.clone]]
address = "4wTV1YmiEkRvAtNtsSGPtUrqRYQMe5SKy2uB4Jjaxnjf"

# fee recipient
[[test.validator.clone]]
address = "CebN5WGQ4jvEPvsVU4EoHEpgzq1VV7AbicfhtW4xC9iM"

# mint
[[test.validator.clone]]
address = "8UrsCAR7XpE8asvAtrErSCRjszcEhHVGLsdtzspgesmB"

# bonding curve
[[test.validator.clone]]
address = "EDDz8NdF1rsQNysSjCtNbJpmTXPgBmvvrumptf3bqZw4"

# associated bonding curve
[[test.validator.clone]]
address = "CkJFiP1t266KjsrnjY65M1PX3MpG5koia4tyoFNiVi5M"

# # system program
# [[test.validator.clone]]
# address = "11111111111111111111111111111111"

# # token program
# [[test.validator.clone]]
# address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
